// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://adcctqyqbdifuntzzwra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkY2N0cXlxYmRpZnVudHp6d3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTcwNDMsImV4cCI6MjA3NDA5MzA0M30.DeGTP1tJZvT3JqWp5A-9C0oZFCFlzyWBJ_tPdAw8t18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
