// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsgrvervaxfpimqnemhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzZ3J2ZXJ2YXhmcGltcW5lbWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Nzg2NzcsImV4cCI6MjA3MTI1NDY3N30.zAY_9EXF6rY4iUHGRR9-lsixrjfAxPzumsvikGUJ974";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});